require('dotenv').config()

const {
  APP_CREDENTIALS_TYPE,
  APP_CREDENTIALS_PROJECT_ID,
  APP_CREDENTIALS_PRIVATE_KEY_ID,
  APP_CREDENTIALS_PRIVATE_KEY,
  APP_CREDENTIALS_CLIENT_EMAIL,
  APP_CREDENTIALS_CLIENT_ID,
  APP_CREDENTIALS_AUTH_URI,
  APP_CREDENTIALS_TOKEN_URI,
  APP_CREDENTIALS_AUTH_PROVIDER,
  APP_CREDENTIALS_CLIENT_CERT_URL,
} = process.env

const GOOGLE_CREDENTIALS = {
  type: APP_CREDENTIALS_TYPE,
  project_id: APP_CREDENTIALS_PROJECT_ID,
  private_key_id: APP_CREDENTIALS_PRIVATE_KEY_ID,
  private_key: APP_CREDENTIALS_PRIVATE_KEY.replace(/\\n/g, '\n'),
  client_email: APP_CREDENTIALS_CLIENT_EMAIL,
  client_id: APP_CREDENTIALS_CLIENT_ID,
  auth_uri: APP_CREDENTIALS_AUTH_URI,
  token_uri: APP_CREDENTIALS_TOKEN_URI,
  auth_provider_x509_cert_url: APP_CREDENTIALS_AUTH_PROVIDER,
  client_x509_cert_url: APP_CREDENTIALS_CLIENT_CERT_URL,
}

export default GOOGLE_CREDENTIALS
